org: devstart
app: image-analysis
service: image-analysis

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 
        - rekognition:DetectLabels
      Resource: '*'
    - Effect: 'Allow'
      Action: 
        - translate:TranslateText
      Resource: '*'

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: /analyse
          method: get